### ISSUE TITLE
Thai Localization - Base Location import from Geonames error!.

### ISSUE THREAD

**Issue by kotchasaan** [OCA/l10n-thailand#158]
ผมได้ทดลองติดตั้งโมดูล Thai Localization - Base Location และทำตามขั้นตอนเพื่อนำเข้าข้อมูลแต่ไม่สำเร็จ โดยมีข้อผิดพลาดตามรายการข้างล่างครับ 
ผิดพลาด:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo13/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo13/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo13/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo13/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo13/odoo-custom-addons/base_location_geonames_import/wizard/geonames_import.py", line 191, in run_import
    parsed_csv = self.get_and_parse_csv(country)
TypeError: get_and_parse_csv() takes 1 positional argument but 2 were given

**Comment by ps-tubtim** [comment]
มีการแก้ไข Error นี้ใน PR: https://github.com/OCA/l10n-thailand/pull/146 ค่ะ

**Comment by kittiu** [comment]
เพิ่งจะ merge Code เข้าไปลองดูใหม่นะครับ

**Comment by kotchasaan** [comment]
ขอบคุณมากครับ

**Comment by kotchasaan** [comment]
ทดสอบติดตั้งดูเหมือนว่าจะหา res.city.zip ไม่พบนะครับต้อง upgrade โมดูลตัวไหนของ odoo ก่อนหรือเปล่า
`ผิดพลาด:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 394, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 987, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
ValueError: Field `district_code` does not exist

Error context:
View `res.city.zip tree`
[view_id: 2279, xml_id: ไม่มีข้อมูล, model: res.city.zip, parent_id: 2196]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/tools/convert.py", line 712, in parse
    self._tag_root(de)
  File "/opt/odoo13/odoo/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/opt/odoo13/odoo/odoo/tools/convert.py", line 577, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/opt/odoo13/odoo/odoo/models.py", line 4080, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/opt/odoo13/odoo/addons/website/models/ir_ui_view.py", line 148, in _load_records_create
    records = super(View, self)._load_records_create(values)
  File "/opt/odoo13/odoo/odoo/models.py", line 3994, in _load_records_create
    return self.create(values)
  File "<decorator-gen-31>", line 2, in create
  File "/opt/odoo13/odoo/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 475, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo13/odoo/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo13/odoo/odoo/models.py", line 3775, in create
    fields[0].determine_inverse(batch_recs)
  File "/opt/odoo13/odoo/odoo/fields.py", line 1114, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 299, in _inverse_arch
    view.write(data)
  File "/opt/odoo13/odoo/addons/website_theme_install/models/theme_models.py", line 224, in write
    res = super(IrUiView, other_views).write(vals)
  File "/opt/odoo13/odoo/addons/website/models/ir_ui_view.py", line 51, in write
    return super(View, self).write(vals)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 493, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo13/odoo/odoo/models.py", line 3564, in write
    real_recs._validate_fields(set(vals) - set(inverse_fields))
  File "/opt/odoo13/odoo/odoo/models.py", line 1176, in _validate_fields
    check(self)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 396, in _check_xml
    raise ValidationError("%s\n\n%s" % (_("Error while validating view"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating view\n\nField `district_code` does not exist\n\nError context:\nView `res.city.zip tree`\n[view_id: 2279, xml_id: ไม่มีข้อมูล, model: res.city.zip, parent_id: 2196]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo13/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo13/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo13/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo13/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-59>", line 2, in button_immediate_install
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo13/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo13/odoo/odoo/modules/loading.py", line 423, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo13/odoo/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo13/odoo/odoo/modules/loading.py", line 225, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/opt/odoo13/odoo/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo13/odoo/odoo/tools/convert.py", line 736, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo13/odoo/odoo/tools/convert.py", line 803, in convert_xml_import
    obj.parse(doc.getroot())
  File "/opt/odoo13/odoo/odoo/tools/convert.py", line 721, in parse
    exc_info[2]
  File "/opt/odoo13/odoo/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo13/odoo/odoo/tools/convert.py", line 712, in parse
    self._tag_root(de)
  File "/opt/odoo13/odoo/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/opt/odoo13/odoo/odoo/tools/convert.py", line 577, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/opt/odoo13/odoo/odoo/models.py", line 4080, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/opt/odoo13/odoo/addons/website/models/ir_ui_view.py", line 148, in _load_records_create
    records = super(View, self)._load_records_create(values)
  File "/opt/odoo13/odoo/odoo/models.py", line 3994, in _load_records_create
    return self.create(values)
  File "<decorator-gen-31>", line 2, in create
  File "/opt/odoo13/odoo/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 475, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo13/odoo/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo13/odoo/odoo/models.py", line 3775, in create
    fields[0].determine_inverse(batch_recs)
  File "/opt/odoo13/odoo/odoo/fields.py", line 1114, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 299, in _inverse_arch
    view.write(data)
  File "/opt/odoo13/odoo/addons/website_theme_install/models/theme_models.py", line 224, in write
    res = super(IrUiView, other_views).write(vals)
  File "/opt/odoo13/odoo/addons/website/models/ir_ui_view.py", line 51, in write
    return super(View, self).write(vals)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 493, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo13/odoo/odoo/models.py", line 3564, in write
    real_recs._validate_fields(set(vals) - set(inverse_fields))
  File "/opt/odoo13/odoo/odoo/models.py", line 1176, in _validate_fields
    check(self)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 396, in _check_xml
    raise ValidationError("%s\n\n%s" % (_("Error while validating view"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating view

Field `district_code` does not exist

Error context:
View `res.city.zip tree`
[view_id: 2279, xml_id: ไม่มีข้อมูล, model: res.city.zip, parent_id: 2196]
None" while parsing /opt/odoo13/l10n-thailand/l10n_th_base_location/views/res_city_zip_view.xml:2, near
<odoo>
    <record id="city_zip_tree" model="ir.ui.view">
        <field name="model">res.city.zip</field>
        <field name="inherit_id" ref="base_location.city_zip_tree"/>
        <field name="arch" type="xml">
            <xpath expr="//tree" position="inside">
                <field name="district_code"/>
                <field name="sub_district_code"/>
            </xpath>
        </field>
    </record>
</odoo>`

**Comment by kotchasaan** [comment]
แก้ปัญหาได้เรียบร้อยโดยการอัพเกรดโมดูล  base_location
