### ISSUE TITLE
[13.0] Tax Report ขึ้น erro ตอนเรียก view report

### ISSUE THREAD

**Issue by Boss1669** [OCA/l10n-thailand#92]
เทสโดย ค่า ตามนี้ครับ
![image](https://user-images.githubusercontent.com/26357404/73513972-6d352e00-4422-11ea-96ed-a106e1caedf1.png)

![image](https://user-images.githubusercontent.com/26357404/73513984-7b834a00-4422-11ea-9fd6-d0d742d14c26.png)

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/api.py", line 753, in get
    value = self._data[field][record._ids[0]]
KeyError: 11

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/fields.py", line 978, in __get__
    value = env.cache.get(record, self)
  File "/odoo/odoo-server/odoo/api.py", line 759, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('report.tax.report(11,).results', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 332, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_l10n_th_tax_report_report_tax_report_base_1916
  File "/odoo/odoo-server/odoo/fields.py", line 2228, in __get__
    return super().__get__(records, owner)
  File "/odoo/odoo-server/odoo/fields.py", line 1002, in __get__
    self.compute_value(recs)
  File "/odoo/odoo-server/odoo/fields.py", line 1087, in compute_value
    records._compute_field_value(self)
  File "/odoo/odoo-server/odoo/models.py", line 3905, in _compute_field_value
    getattr(self, field.compute)()
  File "/odoo/custom/addons/l10n_th_tax_report/reports/tax_report.py", line 71, in _compute_results
    self.company_id.id,
  File "/odoo/odoo-server/odoo/sql_db.py", line 163, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/sql_db.py", line 240, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column t.tax_base_amount does not exist
LINE 8:                 then t.tax_base_amount else 0.0 end as tax_b...
                             ^
HINT:  Perhaps you meant to reference the column "ml.tax_base_amount".


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/api.py", line 753, in get
    value = self._data[field][record._ids[0]]
KeyError: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/fields.py", line 978, in __get__
    value = env.cache.get(record, self)
  File "/odoo/odoo-server/odoo/api.py", line 759, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('res.users(2,).company_id', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 358, in get_template
    document = options.get('load', self.load)(template, options)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_qweb.py", line 116, in load
    lang = options.get('lang', get_lang(self.env).code)
  File "/odoo/odoo-server/odoo/tools/misc.py", line 1176, in get_lang
    for code in [lang_code, env.context.get('lang'), env.user.company_id.partner_id.lang, langs[0]]:
  File "/odoo/odoo-server/odoo/fields.py", line 2228, in __get__
    return super().__get__(records, owner)
  File "/odoo/odoo-server/odoo/fields.py", line 985, in __get__
    recs._fetch_field(self)
  File "/odoo/odoo-server/odoo/models.py", line 2938, in _fetch_field
    self._read(fnames)
  File "/odoo/odoo-server/odoo/addons/base/models/res_users.py", line 378, in _read
    super(Users, self)._read(fields)
  File "/odoo/odoo-server/odoo/models.py", line 3009, in _read
    cr.execute(query_str, params)
  File "/odoo/odoo-server/odoo/sql_db.py", line 163, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/sql_db.py", line 240, in execute
    res = self._obj.execute(query, params)
psycopg2.InternalError: current transaction is aborted, commands ignored until end of transaction block


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1320, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1312, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 391, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 364, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/odoo/custom/addons/l10n_th_tax_report/reports/tax_report.py", line 103, in get_html
    return self.with_context(given_context)._get_html()
  File "/odoo/custom/addons/l10n_th_tax_report/reports/tax_report.py", line 98, in _get_html
    ).render(rcontext)
  File "/odoo/odoo-server/addons/web_editor/models/ir_ui_view.py", line 25, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 1162, in render
    return self.env[engine].render(self.id, qcontext)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_qweb.py", line 58, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 260, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 334, in _compiled_fn
    raise e
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 332, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_l10n_th_tax_report_report_tax_report_html_1900
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 337, in _compiled_fn
    element, document = self.get_template(template, options)
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 364, in get_template
    raise QWebException("load could not load template", e, path, name=template)
odoo.addons.base.models.qweb.QWebException: current transaction is aborted, commands ignored until end of transaction block

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/api.py", line 753, in get
    value = self._data[field][record._ids[0]]
KeyError: 11

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/fields.py", line 978, in __get__
    value = env.cache.get(record, self)
  File "/odoo/odoo-server/odoo/api.py", line 759, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('report.tax.report(11,).results', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 332, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_l10n_th_tax_report_report_tax_report_base_1916
  File "/odoo/odoo-server/odoo/fields.py", line 2228, in __get__
    return super().__get__(records, owner)
  File "/odoo/odoo-server/odoo/fields.py", line 1002, in __get__
    self.compute_value(recs)
  File "/odoo/odoo-server/odoo/fields.py", line 1087, in compute_value
    records._compute_field_value(self)
  File "/odoo/odoo-server/odoo/models.py", line 3905, in _compute_field_value
    getattr(self, field.compute)()
  File "/odoo/custom/addons/l10n_th_tax_report/reports/tax_report.py", line 71, in _compute_results
    self.company_id.id,
  File "/odoo/odoo-server/odoo/sql_db.py", line 163, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/sql_db.py", line 240, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column t.tax_base_amount does not exist
LINE 8:                 then t.tax_base_amount else 0.0 end as tax_b...
                             ^
HINT:  Perhaps you meant to reference the column "ml.tax_base_amount".


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/api.py", line 753, in get
    value = self._data[field][record._ids[0]]
KeyError: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/fields.py", line 978, in __get__
    value = env.cache.get(record, self)
  File "/odoo/odoo-server/odoo/api.py", line 759, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('res.users(2,).company_id', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 358, in get_template
    document = options.get('load', self.load)(template, options)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_qweb.py", line 116, in load
    lang = options.get('lang', get_lang(self.env).code)
  File "/odoo/odoo-server/odoo/tools/misc.py", line 1176, in get_lang
    for code in [lang_code, env.context.get('lang'), env.user.company_id.partner_id.lang, langs[0]]:
  File "/odoo/odoo-server/odoo/fields.py", line 2228, in __get__
    return super().__get__(records, owner)
  File "/odoo/odoo-server/odoo/fields.py", line 985, in __get__
    recs._fetch_field(self)
  File "/odoo/odoo-server/odoo/models.py", line 2938, in _fetch_field
    self._read(fnames)
  File "/odoo/odoo-server/odoo/addons/base/models/res_users.py", line 378, in _read
    super(Users, self)._read(fields)
  File "/odoo/odoo-server/odoo/models.py", line 3009, in _read
    cr.execute(query_str, params)
  File "/odoo/odoo-server/odoo/sql_db.py", line 163, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/sql_db.py", line 240, in execute
    res = self._obj.execute(query, params)
psycopg2.InternalError: current transaction is aborted, commands ignored until end of transaction block


load could not load template
InternalError: current transaction is aborted, commands ignored until end of transaction block

Template: 1440
Path: /t/div/t[2]
```

**Comment by kittiu** [comment]
ขอบคุณที่ทดสอบ
รบกวนลองใหม่อีกครั้ง โดยสร้างเบสใหม่เลยนะครับ
https://github.com/OCA/l10n-thailand/tree/13.0
ผมเพิ่งมปรับปรุงไป ตอนนี้ผม merge PR tax_report ที่ค้างเข้าไปได้แล้ว แต่ report_xlsx_helper ต้องไปเอาของใน PR มาใช้เองนะ

**Comment by Boss1669** [comment]
@kittiu ลองใหม่แล้วนะครับ ยังเป็นขึ้นแบบเดิมเลยครับ ผมไม่แน่ใจผมพลาดตรงไหนหรือเปล่า แต่ว่าลอง install ใน fresh database ก็ยังเป้นเหมือนกันครับ

**Comment by kittiu** [comment]
@kongrattapong พี่รบกวนช่วยดูเคสนี้หน่อยครับ

**Comment by kongrattapong** [comment]
@Boss1669 
ผมลองสร้างเบสใหม่ทดสอบแล้วใช้งานได้ปกตินะครับ
![Selection_148](https://user-images.githubusercontent.com/52144935/73644809-a383df00-46a8-11ea-884d-8cd559d00c73.png)
![Selection_149](https://user-images.githubusercontent.com/52144935/73644808-a383df00-46a8-11ea-81e6-9f922715124d.png)
![Selection_150](https://user-images.githubusercontent.com/52144935/73644807-a2eb4880-46a8-11ea-84ed-64915f102216.png)

ปัญหาอาจจะเกิดเพราะว่า เป็นโค๊ดชุดเก่าหรือเปล่าครับ?
ลองดึงโค๊ดจาก https://github.com/OCA/l10n-thailand/tree/13.0 แล้วทดสอบใหม่หรือยังครับ?

**Comment by kittiu** [comment]
@Boss1669 เคสนี้ยังติดอะไรไม๊

**Comment by Boss1669** [comment]
> @Boss1669 เคสนี้ยังติดอะไรไม๊

ไม่ติดครับขออภัยครับ พอดี modules independencies มีการอัพเดท ครับตอนนี้ได้ปกติแล้วคับ

**Comment by kittiu** [comment]
ครับ ทดสอบแล้วมีอะไรอีกก็บอกมาได้เลย มันอาจยังไม่ perfect ในทุกกรณี ก็ต้องการคนใช้จริงมาบอกนี่ล่ะ :)
